module Evergreen.Migrate.V17 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V12.Domain
import Evergreen.V12.Types
import Evergreen.V17.Domain
import Evergreen.V17.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V12.Types.FrontendModel -> ModelMigration Evergreen.V17.Types.FrontendModel Evergreen.V17.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V12.Types.BackendModel -> ModelMigration Evergreen.V17.Types.BackendModel Evergreen.V17.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V12.Types.FrontendMsg -> MsgMigration Evergreen.V17.Types.FrontendMsg Evergreen.V17.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V12.Types.ToBackend -> MsgMigration Evergreen.V17.Types.ToBackend Evergreen.V17.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V12.Types.BackendMsg -> MsgMigration Evergreen.V17.Types.BackendMsg Evergreen.V17.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V12.Types.ToFrontend -> MsgMigration Evergreen.V17.Types.ToFrontend Evergreen.V17.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V12.Types.BackendModel -> Evergreen.V17.Types.BackendModel
migrate_Types_BackendModel old =
    { events = old.events |> List.map migrate_Domain_Event
    , nextEventId = old.nextEventId
    }


migrate_Types_FrontendModel : Evergreen.V12.Types.FrontendModel -> Evergreen.V17.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , events = old.events |> List.map migrate_Domain_Event
    , form = old.form |> migrate_Types_EventForm
    , editor = old.editor |> migrate_Types_EditorState
    , personFilter = old.personFilter |> migrate_Types_PersonFilter
    , recurrenceFilter = old.recurrenceFilter |> migrate_Types_RecurrenceFilter
    , tagFilter = old.tagFilter |> migrate_Types_TagFilter
    , dateFilter = old.dateFilter |> migrate_Types_DateFilter
    , dateFilterForm = old.dateFilterForm |> migrate_Types_DateFilterForm
    , search = old.search
    , formError = old.formError
    , syncState = old.syncState |> migrate_Types_SyncState
    , notice = old.notice
    , pendingDelete = old.pendingDelete |> Maybe.map migrate_Domain_EventId
    }


migrate_Domain_Assignment : Evergreen.V12.Domain.Assignment -> Evergreen.V17.Domain.Assignment
migrate_Domain_Assignment old =
    case old of
        Evergreen.V12.Domain.OnlyPerson p0 ->
            Evergreen.V17.Domain.OnlyPerson (p0 |> migrate_Domain_Person)

        Evergreen.V12.Domain.BothPeople ->
            Evergreen.V17.Domain.BothPeople


migrate_Domain_CalendarDate : Evergreen.V12.Domain.CalendarDate -> Evergreen.V17.Domain.CalendarDate
migrate_Domain_CalendarDate old =
    case old of
        Evergreen.V12.Domain.CalendarDate p0 ->
            Evergreen.V17.Domain.CalendarDate p0


migrate_Domain_CalendarRange : Evergreen.V12.Domain.CalendarRange -> Evergreen.V17.Domain.CalendarRange
migrate_Domain_CalendarRange old =
    case old of
        Evergreen.V12.Domain.CalendarRange p0 ->
            Evergreen.V17.Domain.CalendarRange
                { start = p0.start |> migrate_Domain_CalendarDate
                , end = p0.end |> migrate_Domain_CalendarDate
                }


migrate_Domain_ClockTime : Evergreen.V12.Domain.ClockTime -> Evergreen.V17.Domain.ClockTime
migrate_Domain_ClockTime old =
    case old of
        Evergreen.V12.Domain.ClockTime p0 ->
            Evergreen.V17.Domain.ClockTime p0


migrate_Domain_Comment : Evergreen.V12.Domain.Comment -> Evergreen.V17.Domain.Comment
migrate_Domain_Comment old =
    case old of
        Evergreen.V12.Domain.NoComment ->
            Evergreen.V17.Domain.NoComment

        Evergreen.V12.Domain.Comment p0 ->
            Evergreen.V17.Domain.Comment p0


migrate_Domain_Event : Evergreen.V12.Domain.Event -> Evergreen.V17.Domain.Event
migrate_Domain_Event old =
    { id = old.id |> migrate_Domain_EventId
    , title = old.title
    , window = old.window |> migrate_Domain_TimeWindow
    , recurrence = old.recurrence |> migrate_Domain_Recurrence
    , assignment = old.assignment |> migrate_Domain_Assignment
    , tags = old.tags |> List.map migrate_Domain_Tag
    , todos = []
    , nextTodoId = 1
    , comment = old.comment |> migrate_Domain_Comment
    , completedOccurrences = old.completedOccurrences |> List.map migrate_Domain_OccurrenceIndex
    }


migrate_Domain_EventDraft : Evergreen.V12.Domain.EventDraft -> Evergreen.V17.Domain.EventDraft
migrate_Domain_EventDraft old =
    { title = old.title
    , window = old.window |> migrate_Domain_TimeWindow
    , recurrence = old.recurrence |> migrate_Domain_Recurrence
    , assignment = old.assignment |> migrate_Domain_Assignment
    , tags = old.tags |> List.map migrate_Domain_Tag
    , todos = []
    , comment = old.comment |> migrate_Domain_Comment
    }


migrate_Domain_EventId : Evergreen.V12.Domain.EventId -> Evergreen.V17.Domain.EventId
migrate_Domain_EventId old =
    case old of
        Evergreen.V12.Domain.EventId p0 ->
            Evergreen.V17.Domain.EventId p0


migrate_Domain_Moment : Evergreen.V12.Domain.Moment -> Evergreen.V17.Domain.Moment
migrate_Domain_Moment old =
    case old of
        Evergreen.V12.Domain.Moment p0 ->
            Evergreen.V17.Domain.Moment
                { date = p0.date |> migrate_Domain_CalendarDate
                , time = p0.time |> migrate_Domain_ClockTime
                }


migrate_Domain_MonthOfYear : Evergreen.V12.Domain.MonthOfYear -> Evergreen.V17.Domain.MonthOfYear
migrate_Domain_MonthOfYear old =
    case old of
        Evergreen.V12.Domain.January ->
            Evergreen.V17.Domain.January

        Evergreen.V12.Domain.February ->
            Evergreen.V17.Domain.February

        Evergreen.V12.Domain.March ->
            Evergreen.V17.Domain.March

        Evergreen.V12.Domain.April ->
            Evergreen.V17.Domain.April

        Evergreen.V12.Domain.May ->
            Evergreen.V17.Domain.May

        Evergreen.V12.Domain.June ->
            Evergreen.V17.Domain.June

        Evergreen.V12.Domain.July ->
            Evergreen.V17.Domain.July

        Evergreen.V12.Domain.August ->
            Evergreen.V17.Domain.August

        Evergreen.V12.Domain.September ->
            Evergreen.V17.Domain.September

        Evergreen.V12.Domain.October ->
            Evergreen.V17.Domain.October

        Evergreen.V12.Domain.November ->
            Evergreen.V17.Domain.November

        Evergreen.V12.Domain.December ->
            Evergreen.V17.Domain.December


migrate_Domain_OccurrenceIndex : Evergreen.V12.Domain.OccurrenceIndex -> Evergreen.V17.Domain.OccurrenceIndex
migrate_Domain_OccurrenceIndex old =
    case old of
        Evergreen.V12.Domain.OccurrenceIndex p0 ->
            Evergreen.V17.Domain.OccurrenceIndex p0


migrate_Domain_Person : Evergreen.V12.Domain.Person -> Evergreen.V17.Domain.Person
migrate_Domain_Person old =
    case old of
        Evergreen.V12.Domain.PersonA ->
            Evergreen.V17.Domain.PersonA

        Evergreen.V12.Domain.PersonB ->
            Evergreen.V17.Domain.PersonB


migrate_Domain_Recurrence : Evergreen.V12.Domain.Recurrence -> Evergreen.V17.Domain.Recurrence
migrate_Domain_Recurrence old =
    case old of
        Evergreen.V12.Domain.OneTime ->
            Evergreen.V17.Domain.OneTime

        Evergreen.V12.Domain.EveryYear ->
            Evergreen.V17.Domain.EveryYear


migrate_Domain_Tag : Evergreen.V12.Domain.Tag -> Evergreen.V17.Domain.Tag
migrate_Domain_Tag old =
    case old of
        Evergreen.V12.Domain.Tag p0 ->
            Evergreen.V17.Domain.Tag p0


migrate_Domain_TimeWindow : Evergreen.V12.Domain.TimeWindow -> Evergreen.V17.Domain.TimeWindow
migrate_Domain_TimeWindow old =
    case old of
        Evergreen.V12.Domain.TimeWindow p0 ->
            Evergreen.V17.Domain.TimeWindow
                { start = p0.start |> migrate_Domain_Moment
                , end = p0.end |> migrate_Domain_Moment
                }


migrate_Types_DateFilter : Evergreen.V12.Types.DateFilter -> Evergreen.V17.Types.DateFilter
migrate_Types_DateFilter old =
    case old of
        Evergreen.V12.Types.AllDates ->
            Evergreen.V17.Types.AllDates

        Evergreen.V12.Types.InMonth p0 ->
            Evergreen.V17.Types.InMonth (p0 |> migrate_Domain_MonthOfYear)

        Evergreen.V12.Types.InRange p0 ->
            Evergreen.V17.Types.InRange (p0 |> migrate_Domain_CalendarRange)


migrate_Types_DateFilterForm : Evergreen.V12.Types.DateFilterForm -> Evergreen.V17.Types.DateFilterForm
migrate_Types_DateFilterForm old =
    old


migrate_Types_EditorState : Evergreen.V12.Types.EditorState -> Evergreen.V17.Types.EditorState
migrate_Types_EditorState old =
    case old of
        Evergreen.V12.Types.EditorClosed ->
            Evergreen.V17.Types.EditorClosed

        Evergreen.V12.Types.CreatingEvent ->
            Evergreen.V17.Types.CreatingEvent

        Evergreen.V12.Types.DuplicatingEvent ->
            Evergreen.V17.Types.DuplicatingEvent

        Evergreen.V12.Types.EditingEvent p0 ->
            Evergreen.V17.Types.EditingEvent (p0 |> migrate_Domain_EventId)


migrate_Types_EventForm : Evergreen.V12.Types.EventForm -> Evergreen.V17.Types.EventForm
migrate_Types_EventForm old =
    { title = old.title
    , startDate = old.startDate
    , startTime = old.startTime
    , endDate = old.endDate
    , endTime = old.endTime
    , recurrence = old.recurrence |> migrate_Domain_Recurrence
    , assignment = old.assignment |> migrate_Domain_Assignment
    , tags = old.tags
    , todos = ""
    , comment = old.comment
    }


migrate_Types_FrontendMsg : Evergreen.V12.Types.FrontendMsg -> Evergreen.V17.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V12.Types.UrlClicked p0 ->
            Evergreen.V17.Types.UrlClicked p0

        Evergreen.V12.Types.UrlChanged p0 ->
            Evergreen.V17.Types.UrlChanged p0

        Evergreen.V12.Types.OpenCreateEditor ->
            Evergreen.V17.Types.OpenCreateEditor

        Evergreen.V12.Types.OpenDuplicateEditor p0 ->
            Evergreen.V17.Types.OpenDuplicateEditor (p0 |> migrate_Domain_EventId)

        Evergreen.V12.Types.OpenEditEditor p0 ->
            Evergreen.V17.Types.OpenEditEditor (p0 |> migrate_Domain_EventId)

        Evergreen.V12.Types.CloseEditor ->
            Evergreen.V17.Types.CloseEditor

        Evergreen.V12.Types.ChangeTitle p0 ->
            Evergreen.V17.Types.ChangeTitle p0

        Evergreen.V12.Types.ChangeStartDate p0 ->
            Evergreen.V17.Types.ChangeStartDate p0

        Evergreen.V12.Types.ChangeStartTime p0 ->
            Evergreen.V17.Types.ChangeStartTime p0

        Evergreen.V12.Types.ChangeEndDate p0 ->
            Evergreen.V17.Types.ChangeEndDate p0

        Evergreen.V12.Types.ChangeEndTime p0 ->
            Evergreen.V17.Types.ChangeEndTime p0

        Evergreen.V12.Types.ChangeRecurrence p0 ->
            Evergreen.V17.Types.ChangeRecurrence (p0 |> migrate_Domain_Recurrence)

        Evergreen.V12.Types.ChangeAssignment p0 ->
            Evergreen.V17.Types.ChangeAssignment (p0 |> migrate_Domain_Assignment)

        Evergreen.V12.Types.ChangeTags p0 ->
            Evergreen.V17.Types.ChangeTags p0

        Evergreen.V12.Types.ChangeComment p0 ->
            Evergreen.V17.Types.ChangeComment p0

        Evergreen.V12.Types.SubmitEvent ->
            Evergreen.V17.Types.SubmitEvent

        Evergreen.V12.Types.ChangePersonFilter p0 ->
            Evergreen.V17.Types.ChangePersonFilter (p0 |> migrate_Types_PersonFilter)

        Evergreen.V12.Types.ChangeRecurrenceFilter p0 ->
            Evergreen.V17.Types.ChangeRecurrenceFilter (p0 |> migrate_Types_RecurrenceFilter)

        Evergreen.V12.Types.ChangeTagFilter p0 ->
            Evergreen.V17.Types.ChangeTagFilter (p0 |> migrate_Types_TagFilter)

        Evergreen.V12.Types.ChangeMonthFilter p0 ->
            Evergreen.V17.Types.ChangeMonthFilter p0

        Evergreen.V12.Types.ChangeRangeStart p0 ->
            Evergreen.V17.Types.ChangeRangeStart p0

        Evergreen.V12.Types.ChangeRangeEnd p0 ->
            Evergreen.V17.Types.ChangeRangeEnd p0

        Evergreen.V12.Types.ApplyDateRange ->
            Evergreen.V17.Types.ApplyDateRange

        Evergreen.V12.Types.ClearDateFilter ->
            Evergreen.V17.Types.ClearDateFilter

        Evergreen.V12.Types.ChangeSearch p0 ->
            Evergreen.V17.Types.ChangeSearch p0

        Evergreen.V12.Types.ResetFilters ->
            Evergreen.V17.Types.ResetFilters

        Evergreen.V12.Types.AskDelete p0 ->
            Evergreen.V17.Types.AskDelete (p0 |> migrate_Domain_EventId)

        Evergreen.V12.Types.CancelDelete ->
            Evergreen.V17.Types.CancelDelete

        Evergreen.V12.Types.ConfirmDelete p0 ->
            Evergreen.V17.Types.ConfirmDelete (p0 |> migrate_Domain_EventId)

        Evergreen.V12.Types.ToggleOccurrence p0 p1 ->
            Evergreen.V17.Types.ToggleOccurrence (p0 |> migrate_Domain_EventId)
                (p1 |> migrate_Domain_OccurrenceIndex)

        Evergreen.V12.Types.DismissNotice ->
            Evergreen.V17.Types.DismissNotice


migrate_Types_PersonFilter : Evergreen.V12.Types.PersonFilter -> Evergreen.V17.Types.PersonFilter
migrate_Types_PersonFilter old =
    case old of
        Evergreen.V12.Types.AllPeople ->
            Evergreen.V17.Types.AllPeople

        Evergreen.V12.Types.AssignedTo p0 ->
            Evergreen.V17.Types.AssignedTo (p0 |> migrate_Domain_Person)


migrate_Types_RecurrenceFilter : Evergreen.V12.Types.RecurrenceFilter -> Evergreen.V17.Types.RecurrenceFilter
migrate_Types_RecurrenceFilter old =
    case old of
        Evergreen.V12.Types.AllRecurrences ->
            Evergreen.V17.Types.AllRecurrences

        Evergreen.V12.Types.OnlyRecurrence p0 ->
            Evergreen.V17.Types.OnlyRecurrence (p0 |> migrate_Domain_Recurrence)


migrate_Types_SyncState : Evergreen.V12.Types.SyncState -> Evergreen.V17.Types.SyncState
migrate_Types_SyncState old =
    case old of
        Evergreen.V12.Types.Loading ->
            Evergreen.V17.Types.Loading

        Evergreen.V12.Types.Synced ->
            Evergreen.V17.Types.Synced

        Evergreen.V12.Types.Saving ->
            Evergreen.V17.Types.Saving

        Evergreen.V12.Types.SyncFailed p0 ->
            Evergreen.V17.Types.SyncFailed p0


migrate_Types_TagFilter : Evergreen.V12.Types.TagFilter -> Evergreen.V17.Types.TagFilter
migrate_Types_TagFilter old =
    case old of
        Evergreen.V12.Types.AllTags ->
            Evergreen.V17.Types.AllTags

        Evergreen.V12.Types.TaggedWith p0 ->
            Evergreen.V17.Types.TaggedWith (p0 |> migrate_Domain_Tag)


migrate_Types_ToBackend : Evergreen.V12.Types.ToBackend -> Evergreen.V17.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V12.Types.RequestEvents ->
            Evergreen.V17.Types.RequestEvents

        Evergreen.V12.Types.CreateEvent p0 ->
            Evergreen.V17.Types.CreateEvent (p0 |> migrate_Domain_EventDraft)

        Evergreen.V12.Types.UpdateEvent p0 p1 ->
            Evergreen.V17.Types.UpdateEvent (p0 |> migrate_Domain_EventId)
                (p1 |> migrate_Domain_EventDraft)

        Evergreen.V12.Types.DeleteEvent p0 ->
            Evergreen.V17.Types.DeleteEvent (p0 |> migrate_Domain_EventId)

        Evergreen.V12.Types.ToggleOccurrenceCompletion p0 p1 ->
            Evergreen.V17.Types.ToggleOccurrenceCompletion (p0 |> migrate_Domain_EventId)
                (p1 |> migrate_Domain_OccurrenceIndex)


migrate_Types_ToFrontend : Evergreen.V12.Types.ToFrontend -> Evergreen.V17.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V12.Types.EventsLoaded p0 ->
            Evergreen.V17.Types.EventsLoaded (p0 |> List.map migrate_Domain_Event)

        Evergreen.V12.Types.EventsChanged p0 p1 ->
            Evergreen.V17.Types.EventsChanged (p0 |> List.map migrate_Domain_Event) p1

        Evergreen.V12.Types.ChangeRejected p0 ->
            Evergreen.V17.Types.ChangeRejected p0
