module Evergreen.Migrate.V9 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V3.Domain
import Evergreen.V3.Types
import Evergreen.V9.Domain
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V9.Types.FrontendModel Evergreen.V9.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V9.Types.BackendModel Evergreen.V9.Types.BackendMsg
backendModel old =
    ModelMigrated
        ( { events = old.events |> List.map migrate_Domain_Event
          , nextEventId = old.nextEventId
          }
        , Cmd.none
        )


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V9.Types.FrontendMsg Evergreen.V9.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V9.Types.ToBackend Evergreen.V9.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V9.Types.BackendMsg Evergreen.V9.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V9.Types.ToFrontend Evergreen.V9.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V3.Types.FrontendModel -> Evergreen.V9.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , events = old.events |> List.map migrate_Domain_Event
    , form = old.form |> migrate_Types_EventForm
    , editor = old.editor |> migrate_Types_EditorState
    , personFilter = old.personFilter |> migrate_Types_PersonFilter
    , recurrenceFilter = old.recurrenceFilter |> migrate_Types_RecurrenceFilter
    , dateFilter = Evergreen.V9.Types.AllDates
    , dateFilterForm =
        { month = ""
        , rangeStart = ""
        , rangeEnd = ""
        , error = Nothing
        }
    , search = old.search
    , formError = old.formError
    , syncState = old.syncState |> migrate_Types_SyncState
    , notice = old.notice
    , pendingDelete = old.pendingDelete |> Maybe.map migrate_Domain_EventId
    }


migrate_Domain_Assignment : Evergreen.V3.Domain.Assignment -> Evergreen.V9.Domain.Assignment
migrate_Domain_Assignment old =
    case old of
        Evergreen.V3.Domain.OnlyPerson p0 ->
            Evergreen.V9.Domain.OnlyPerson (p0 |> migrate_Domain_Person)

        Evergreen.V3.Domain.BothPeople ->
            Evergreen.V9.Domain.BothPeople


migrate_Domain_CalendarDate : Evergreen.V3.Domain.CalendarDate -> Evergreen.V9.Domain.CalendarDate
migrate_Domain_CalendarDate old =
    case old of
        Evergreen.V3.Domain.CalendarDate p0 ->
            Evergreen.V9.Domain.CalendarDate p0


migrate_Domain_ClockTime : Evergreen.V3.Domain.ClockTime -> Evergreen.V9.Domain.ClockTime
migrate_Domain_ClockTime old =
    case old of
        Evergreen.V3.Domain.ClockTime p0 ->
            Evergreen.V9.Domain.ClockTime p0


migrate_Domain_Comment : Evergreen.V3.Domain.Comment -> Evergreen.V9.Domain.Comment
migrate_Domain_Comment old =
    case old of
        Evergreen.V3.Domain.NoComment ->
            Evergreen.V9.Domain.NoComment

        Evergreen.V3.Domain.Comment p0 ->
            Evergreen.V9.Domain.Comment p0


migrate_Domain_Event : Evergreen.V3.Domain.Event -> Evergreen.V9.Domain.Event
migrate_Domain_Event old =
    { id = old.id |> migrate_Domain_EventId
    , title = old.title
    , window = old.window |> migrate_Domain_TimeWindow
    , recurrence = old.recurrence |> migrate_Domain_Recurrence
    , assignment = old.assignment |> migrate_Domain_Assignment
    , comment = old.comment |> migrate_Domain_Comment
    , completedOccurrences = migrateCompletedOccurrences old.recurrence old.completedOccurrences
    }


migrate_Domain_EventId : Evergreen.V3.Domain.EventId -> Evergreen.V9.Domain.EventId
migrate_Domain_EventId old =
    case old of
        Evergreen.V3.Domain.EventId p0 ->
            Evergreen.V9.Domain.EventId p0


migrate_Domain_EventDraft : Evergreen.V3.Domain.EventDraft -> Evergreen.V9.Domain.EventDraft
migrate_Domain_EventDraft old =
    { title = old.title
    , window = old.window |> migrate_Domain_TimeWindow
    , recurrence = old.recurrence |> migrate_Domain_Recurrence
    , assignment = old.assignment |> migrate_Domain_Assignment
    , comment = old.comment |> migrate_Domain_Comment
    }


migrate_Domain_Moment : Evergreen.V3.Domain.Moment -> Evergreen.V9.Domain.Moment
migrate_Domain_Moment old =
    case old of
        Evergreen.V3.Domain.Moment p0 ->
            Evergreen.V9.Domain.Moment
                { date = p0.date |> migrate_Domain_CalendarDate
                , time = p0.time |> migrate_Domain_ClockTime
                }


migrate_Domain_OccurrenceIndex : Evergreen.V3.Domain.OccurrenceIndex -> Evergreen.V9.Domain.OccurrenceIndex
migrate_Domain_OccurrenceIndex old =
    case old of
        Evergreen.V3.Domain.OccurrenceIndex p0 ->
            Evergreen.V9.Domain.OccurrenceIndex p0


migrateCompletedOccurrences : Evergreen.V3.Domain.Recurrence -> List Evergreen.V3.Domain.OccurrenceIndex -> List Evergreen.V9.Domain.OccurrenceIndex
migrateCompletedOccurrences recurrence completedOccurrences =
    case recurrence of
        Evergreen.V3.Domain.EverySemester ->
            completedOccurrences
                |> List.filterMap
                    (\(Evergreen.V3.Domain.OccurrenceIndex index) ->
                        if modBy 2 index == 0 then
                            Just (Evergreen.V9.Domain.OccurrenceIndex (index // 2))

                        else
                            Nothing
                    )

        _ ->
            completedOccurrences |> List.map migrate_Domain_OccurrenceIndex


migrate_Domain_Person : Evergreen.V3.Domain.Person -> Evergreen.V9.Domain.Person
migrate_Domain_Person old =
    case old of
        Evergreen.V3.Domain.PersonA ->
            Evergreen.V9.Domain.PersonA

        Evergreen.V3.Domain.PersonB ->
            Evergreen.V9.Domain.PersonB


migrate_Domain_Recurrence : Evergreen.V3.Domain.Recurrence -> Evergreen.V9.Domain.Recurrence
migrate_Domain_Recurrence old =
    case old of
        Evergreen.V3.Domain.OneTime ->
            Evergreen.V9.Domain.OneTime

        Evergreen.V3.Domain.EverySemester ->
            Evergreen.V9.Domain.EveryYear

        Evergreen.V3.Domain.EveryYear ->
            Evergreen.V9.Domain.EveryYear


migrate_Domain_TimeWindow : Evergreen.V3.Domain.TimeWindow -> Evergreen.V9.Domain.TimeWindow
migrate_Domain_TimeWindow old =
    case old of
        Evergreen.V3.Domain.TimeWindow p0 ->
            Evergreen.V9.Domain.TimeWindow
                { start = p0.start |> migrate_Domain_Moment
                , end = p0.end |> migrate_Domain_Moment
                }


migrate_Types_EditorState : Evergreen.V3.Types.EditorState -> Evergreen.V9.Types.EditorState
migrate_Types_EditorState old =
    case old of
        Evergreen.V3.Types.EditorClosed ->
            Evergreen.V9.Types.EditorClosed

        Evergreen.V3.Types.CreatingEvent ->
            Evergreen.V9.Types.CreatingEvent

        Evergreen.V3.Types.EditingEvent p0 ->
            Evergreen.V9.Types.EditingEvent (p0 |> migrate_Domain_EventId)


migrate_Types_EventForm : Evergreen.V3.Types.EventForm -> Evergreen.V9.Types.EventForm
migrate_Types_EventForm old =
    { title = old.title
    , startDate = old.startDate
    , startTime = old.startTime
    , endDate = old.endDate
    , endTime = old.endTime
    , recurrence = old.recurrence |> migrate_Domain_Recurrence
    , assignment = old.assignment |> migrate_Domain_Assignment
    , comment = old.comment
    }


migrate_Types_FrontendMsg : Evergreen.V3.Types.FrontendMsg -> Evergreen.V9.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V3.Types.UrlClicked p0 ->
            Evergreen.V9.Types.UrlClicked p0

        Evergreen.V3.Types.UrlChanged p0 ->
            Evergreen.V9.Types.UrlChanged p0

        Evergreen.V3.Types.OpenCreateEditor ->
            Evergreen.V9.Types.OpenCreateEditor

        Evergreen.V3.Types.OpenEditEditor p0 ->
            Evergreen.V9.Types.OpenEditEditor (p0 |> migrate_Domain_EventId)

        Evergreen.V3.Types.CloseEditor ->
            Evergreen.V9.Types.CloseEditor

        Evergreen.V3.Types.ChangeTitle p0 ->
            Evergreen.V9.Types.ChangeTitle p0

        Evergreen.V3.Types.ChangeStartDate p0 ->
            Evergreen.V9.Types.ChangeStartDate p0

        Evergreen.V3.Types.ChangeStartTime p0 ->
            Evergreen.V9.Types.ChangeStartTime p0

        Evergreen.V3.Types.ChangeEndDate p0 ->
            Evergreen.V9.Types.ChangeEndDate p0

        Evergreen.V3.Types.ChangeEndTime p0 ->
            Evergreen.V9.Types.ChangeEndTime p0

        Evergreen.V3.Types.ChangeRecurrence p0 ->
            Evergreen.V9.Types.ChangeRecurrence (p0 |> migrate_Domain_Recurrence)

        Evergreen.V3.Types.ChangeAssignment p0 ->
            Evergreen.V9.Types.ChangeAssignment (p0 |> migrate_Domain_Assignment)

        Evergreen.V3.Types.ChangeComment p0 ->
            Evergreen.V9.Types.ChangeComment p0

        Evergreen.V3.Types.SubmitEvent ->
            Evergreen.V9.Types.SubmitEvent

        Evergreen.V3.Types.ChangePersonFilter p0 ->
            Evergreen.V9.Types.ChangePersonFilter (p0 |> migrate_Types_PersonFilter)

        Evergreen.V3.Types.ChangeRecurrenceFilter p0 ->
            Evergreen.V9.Types.ChangeRecurrenceFilter (p0 |> migrate_Types_RecurrenceFilter)

        Evergreen.V3.Types.ChangeSearch p0 ->
            Evergreen.V9.Types.ChangeSearch p0

        Evergreen.V3.Types.ResetFilters ->
            Evergreen.V9.Types.ResetFilters

        Evergreen.V3.Types.AskDelete p0 ->
            Evergreen.V9.Types.AskDelete (p0 |> migrate_Domain_EventId)

        Evergreen.V3.Types.CancelDelete ->
            Evergreen.V9.Types.CancelDelete

        Evergreen.V3.Types.ConfirmDelete p0 ->
            Evergreen.V9.Types.ConfirmDelete (p0 |> migrate_Domain_EventId)

        Evergreen.V3.Types.ToggleOccurrence p0 p1 ->
            Evergreen.V9.Types.ToggleOccurrence (p0 |> migrate_Domain_EventId)
                (p1 |> migrate_Domain_OccurrenceIndex)

        Evergreen.V3.Types.DismissNotice ->
            Evergreen.V9.Types.DismissNotice


migrate_Types_PersonFilter : Evergreen.V3.Types.PersonFilter -> Evergreen.V9.Types.PersonFilter
migrate_Types_PersonFilter old =
    case old of
        Evergreen.V3.Types.AllPeople ->
            Evergreen.V9.Types.AllPeople

        Evergreen.V3.Types.AssignedTo p0 ->
            Evergreen.V9.Types.AssignedTo (p0 |> migrate_Domain_Person)


migrate_Types_RecurrenceFilter : Evergreen.V3.Types.RecurrenceFilter -> Evergreen.V9.Types.RecurrenceFilter
migrate_Types_RecurrenceFilter old =
    case old of
        Evergreen.V3.Types.AllRecurrences ->
            Evergreen.V9.Types.AllRecurrences

        Evergreen.V3.Types.OnlyRecurrence Evergreen.V3.Domain.EverySemester ->
            Evergreen.V9.Types.AllRecurrences

        Evergreen.V3.Types.OnlyRecurrence p0 ->
            Evergreen.V9.Types.OnlyRecurrence (p0 |> migrate_Domain_Recurrence)


migrate_Types_SyncState : Evergreen.V3.Types.SyncState -> Evergreen.V9.Types.SyncState
migrate_Types_SyncState old =
    case old of
        Evergreen.V3.Types.Loading ->
            Evergreen.V9.Types.Loading

        Evergreen.V3.Types.Synced ->
            Evergreen.V9.Types.Synced

        Evergreen.V3.Types.Saving ->
            Evergreen.V9.Types.Saving

        Evergreen.V3.Types.SyncFailed p0 ->
            Evergreen.V9.Types.SyncFailed p0


migrate_Types_ToBackend : Evergreen.V3.Types.ToBackend -> Evergreen.V9.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V3.Types.RequestEvents ->
            Evergreen.V9.Types.RequestEvents

        Evergreen.V3.Types.CreateEvent p0 ->
            Evergreen.V9.Types.CreateEvent (p0 |> migrate_Domain_EventDraft)

        Evergreen.V3.Types.UpdateEvent p0 p1 ->
            Evergreen.V9.Types.UpdateEvent
                (p0 |> migrate_Domain_EventId)
                (p1 |> migrate_Domain_EventDraft)

        Evergreen.V3.Types.DeleteEvent p0 ->
            Evergreen.V9.Types.DeleteEvent (p0 |> migrate_Domain_EventId)

        Evergreen.V3.Types.ToggleOccurrenceCompletion p0 p1 ->
            Evergreen.V9.Types.ToggleOccurrenceCompletion
                (p0 |> migrate_Domain_EventId)
                (p1 |> migrate_Domain_OccurrenceIndex)


migrate_Types_ToFrontend : Evergreen.V3.Types.ToFrontend -> Evergreen.V9.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V3.Types.EventsLoaded p0 ->
            Evergreen.V9.Types.EventsLoaded (p0 |> List.map migrate_Domain_Event)

        Evergreen.V3.Types.EventsChanged p0 p1 ->
            Evergreen.V9.Types.EventsChanged
                (p0 |> List.map migrate_Domain_Event)
                p1

        Evergreen.V3.Types.ChangeRejected p0 ->
            Evergreen.V9.Types.ChangeRejected p0
